Repository se-mi-col-on/Viewtist_BE, pull requests merged in 2024-03, with the labels that each got.

#12 [docker] docker-compose 수정
  docker-compose.yml
  domain/Dockerfile
Labels: fix

#9 [#27]WebSocket을 이용한 실시간 채팅 설정
  build.gradle
  chatting-api/build.gradle
  chatting-api/src/main/java/semicolon/viewtist/ChattingApplication.java
  chatting-api/src/main/java/semicolon/viewtist/controller/LiveChatController.java
  chatting-api/src/main/java/semicolon/viewtist/controller/controller.java
  chatting-api/src/main/java/semicolon/viewtist/exception/ChattingException.java
  chatting-api/src/main/java/semicolon/viewtist/exception/ErrorCode.java
  chatting-api/src/main/java/semicolon/viewtist/service/LiveChatService.java
  chatting-api/src/main/java/semicolon/viewtist/websocket/WebSocketChatHandler.java
  chatting-api/src/main/java/semicolon/viewtist/websocket/WebSocketConfig.java
  domain/build.gradle
  domain/src/main/java/semicolon/viewtis/chatting/dto/ChatMessageDto.java
  domain/src/main/java/semicolon/viewtis/chatting/dto/ChatRoomDto.java
  domain/src/main/java/semicolon/viewtis/chatting/entity/ChatMessage.java
  domain/src/main/java/semicolon/viewtis/chatting/entity/ChatRoom.java
  domain/src/main/java/semicolon/viewtis/chatting/form/ChatRoomForm.java
  domain/src/main/java/semicolon/viewtis/chatting/repository/ChatMessageRepository.java
  domain/src/main/java/semicolon/viewtis/chatting/repository/ChatRoomRepository.java
  domain/src/main/java/semicolon/viewtis/core/global/BaseTimeEntity.java
Labels: feature

#15 [#27] WebSocket을 이용한 실시간 채팅 설정
  build.gradle
  chatting-api/build.gradle
  chatting-api/src/main/java/semicolon/viewtist/ChattingApplication.java
  chatting-api/src/main/java/semicolon/viewtist/controller/LiveChatController.java
  chatting-api/src/main/java/semicolon/viewtist/controller/controller.java
  chatting-api/src/main/java/semicolon/viewtist/exception/ChattingException.java
  chatting-api/src/main/java/semicolon/viewtist/exception/ErrorCode.java
  chatting-api/src/main/java/semicolon/viewtist/service/LiveChatService.java
  chatting-api/src/main/java/semicolon/viewtist/websocket/WebSocketChatHandler.java
  chatting-api/src/main/java/semicolon/viewtist/websocket/WebSocketConfig.java
  domain/build.gradle
  domain/src/main/java/semicolon/viewtis/chatting/dto/ChatMessageDto.java
  domain/src/main/java/semicolon/viewtis/chatting/dto/ChatRoomDto.java
  domain/src/main/java/semicolon/viewtis/chatting/entity/ChatMessage.java
  domain/src/main/java/semicolon/viewtis/chatting/entity/ChatRoom.java
  domain/src/main/java/semicolon/viewtis/chatting/form/ChatRoomForm.java
  domain/src/main/java/semicolon/viewtis/chatting/repository/ChatMessageRepository.java
  domain/src/main/java/semicolon/viewtis/chatting/repository/ChatRoomRepository.java
  domain/src/main/java/semicolon/viewtis/core/global/BaseTimeEntity.java
Labels: feature

#16 [#2] 리펙토링 로그인 기능 관련 로직 개선 및 Entity 관련 @Setter 삭제
  .github/workflows/gradle.yml
  core/src/main/java/semicolon/viewtist/jwt/TokenProvider.java
  core/src/main/java/semicolon/viewtist/s3/AmazonConfig.java
  core/src/main/java/semicolon/viewtist/s3/S3UploaderService.java
  core/src/main/java/semicolon/viewtist/s3/s3Uploader/S3Uploader.java
  core/src/main/java/semicolon/viewtist/user/controller/AuthController.java
  core/src/main/java/semicolon/viewtist/user/controller/UserController.java
  core/src/main/java/semicolon/viewtist/user/handler/OAuth2SuccessHandler.java
  core/src/main/java/semicolon/viewtist/user/service/AuthService.java
  core/src/main/java/semicolon/viewtist/user/service/OAuth2UserServiceImplement.java
  core/src/main/java/semicolon/viewtist/user/service/UserService.java
  domain/src/main/java/semicolon/viewtist/global/exception/ErrorCode.java
  domain/src/main/java/semicolon/viewtist/image/entity/Image.java
  domain/src/main/java/semicolon/viewtist/jwt/entity/TokenBlacklist.java
  domain/src/main/java/semicolon/viewtist/user/dto/UserDto.java
  domain/src/main/java/semicolon/viewtist/user/dto/request/UpdatePasswordRequest.java
  domain/src/main/java/semicolon/viewtist/user/dto/request/UserSiginupRequest.java
  domain/src/main/java/semicolon/viewtist/user/dto/response/UserResponse.java
  domain/src/main/java/semicolon/viewtist/user/entity/Account.java
  domain/src/main/java/semicolon/viewtist/user/entity/User.java
  streaming-api/build.gradle
Labels: refactor

#17 [doc] oauth관련 파일 core로 이동
  core/src/main/java/semicolon/viewtist/config/SecurityConfig.java
  core/src/main/java/semicolon/viewtist/oauth/CustomOAuth2User.java
  core/src/main/java/semicolon/viewtist/oauth/OAuth2UserServiceImplement.java
  core/src/main/java/semicolon/viewtist/oauth/handler/OAuth2SuccessHandler.java
  domain/build.gradle
Labels: documentation

#18 [#48] Refactor/websocket setting entity & dto 리펙토링
  chatting-api/src/main/java/semicolon/viewtist/ChattingApplication.java
  chatting-api/src/main/java/semicolon/viewtist/config/SwaggerConfig.java
  chatting-api/src/main/java/semicolon/viewtist/controller/LiveChatController.java
  chatting-api/src/main/java/semicolon/viewtist/exception/ChattingException.java
  chatting-api/src/main/java/semicolon/viewtist/exception/ErrorCode.java
  chatting-api/src/main/java/semicolon/viewtist/service/LiveChatService.java
  chatting-api/src/main/java/semicolon/viewtist/websocket/WebSocketChatHandler.java
  domain/build.gradle
  domain/src/main/java/semicolon/viewtis/core/global/BaseTimeEntity.java
  domain/src/main/java/semicolon/viewtist/chatting/dto/request/ChatMessageRequest.java
  domain/src/main/java/semicolon/viewtist/chatting/dto/request/ChatRoomRequest.java
  domain/src/main/java/semicolon/viewtist/chatting/dto/response/ChatRoomResponse.java
  domain/src/main/java/semicolon/viewtist/chatting/entity/ChatMessage.java
  domain/src/main/java/semicolon/viewtist/chatting/entity/ChatRoom.java
  domain/src/main/java/semicolon/viewtist/chatting/repository/ChatMessageRepository.java
  domain/src/main/java/semicolon/viewtist/chatting/repository/ChatRoomRepository.java
  domain/src/main/java/semicolon/viewtist/global/exception/ErrorCode.java
Labels: fix

#22 [#35] 스트리밍 시작 기능
  .github/workflows/gradle.yml
  domain/src/main/java/semicolon/viewtist/liveStreaming/dto/request/LiveStreamingCreateRequest.java
  domain/src/main/java/semicolon/viewtist/liveStreaming/dto/request/LiveStreamingUpdateRequest.java
  domain/src/main/java/semicolon/viewtist/liveStreaming/dto/response/LiveStreamingResponse.java
  domain/src/main/java/semicolon/viewtist/liveStreaming/entity/Category.java
  domain/src/main/java/semicolon/viewtist/liveStreaming/entity/LiveStreaming.java
  domain/src/main/java/semicolon/viewtist/liveStreaming/exception/LiveStreamingException.java
  domain/src/main/java/semicolon/viewtist/liveStreaming/repository/LiveStreamingRepository.java
  streaming-api/build.gradle
  streaming-api/src/main/java/semicolon/viewtist/config/SecurityConfig.java
  streaming-api/src/main/java/semicolon/viewtist/config/SwaggerConfig.java
  streaming-api/src/main/java/semicolon/viewtist/cotroller/LiveStreamingController.java
  streaming-api/src/main/java/semicolon/viewtist/service/LiveStreamingService.java
Labels: feature

#25 [Setting] core -> common 네이밍 변경
  .github/workflows/gradle.yml
  common/Dockerfile
  common/build.gradle
  common/src/main/java/semicolon/viewtist/CommonApplication.java
  common/src/main/java/semicolon/viewtist/config/SecurityConfig.java
  common/src/main/java/semicolon/viewtist/config/SwaggerConfig.java
  common/src/main/java/semicolon/viewtist/mailgun/FeignConfig.java
  common/src/main/java/semicolon/viewtist/mailgun/MailgunClient.java
  common/src/main/java/semicolon/viewtist/mailgun/SendMailForm.java
  common/src/main/java/semicolon/viewtist/oauth/CustomOAuth2User.java
  common/src/main/java/semicolon/viewtist/oauth/OAuth2UserServiceImplement.java
  common/src/main/java/semicolon/viewtist/oauth/handler/OAuth2SuccessHandler.java
  common/src/main/java/semicolon/viewtist/s3/AmazonConfig.java
  common/src/main/java/semicolon/viewtist/s3/S3UploaderService.java
  common/src/main/java/semicolon/viewtist/user/controller/AuthController.java
  common/src/main/java/semicolon/viewtist/user/controller/UserController.java
  common/src/main/java/semicolon/viewtist/user/service/AuthService.java
  common/src/main/java/semicolon/viewtist/user/service/UserService.java
  common/src/test/java/auth.http
  docker-compose.yml
  settings.gradle
Labels: documentation

#28 [refactor] 피드백 반영
  .github/workflows/gradle.yml
  common/src/main/java/semicolon/viewtist/oauth/OAuth2UserServiceImplement.java
  common/src/main/java/semicolon/viewtist/user/controller/AuthController.java
  common/src/main/java/semicolon/viewtist/user/controller/UserController.java
  common/src/main/java/semicolon/viewtist/user/service/AuthService.java
  common/src/main/java/semicolon/viewtist/user/service/UserService.java
  domain/src/main/java/semicolon/viewtist/global/exception/ErrorCode.java
  domain/src/main/java/semicolon/viewtist/jwt/TokenProvider.java
  domain/src/main/java/semicolon/viewtist/user/dto/request/SocialUserRequest.java
  domain/src/main/java/semicolon/viewtist/user/dto/request/UserSignupRequest.java
  domain/src/main/java/semicolon/viewtist/user/entity/Type.java
  domain/src/main/java/semicolon/viewtist/user/entity/User.java
Labels: refactor

#29 [fix] 토큰값 저장 문제 해결
  common/build.gradle
  common/src/main/java/semicolon/viewtist/oauth/OAuth2UserServiceImplement.java
  common/src/main/java/semicolon/viewtist/user/service/AuthService.java
Labels: fix

#32 [#40] 채팅방 API
  build.gradle
  chatting-api/build.gradle
  chatting-api/src/main/java/semicolon/viewtist/ChattingApplication.java
  chatting-api/src/main/java/semicolon/viewtist/config/StompConfig.java
  chatting-api/src/main/java/semicolon/viewtist/controller/ChatRoomController.java
  chatting-api/src/main/java/semicolon/viewtist/service/ChatRoomService.java
  chatting-api/src/main/java/semicolon/viewtist/stomp/StompHandler.java
  chatting-api/src/main/java/semicolon/viewtist/websocket/WebSocketChatHandler.java
  domain/src/main/java/semicolon/viewtist/chatting/dto/request/ChatRoomRequest.java
  domain/src/main/java/semicolon/viewtist/chatting/dto/response/ChatRoomResponse.java
  domain/src/main/java/semicolon/viewtist/chatting/entity/ChatRoom.java
  domain/src/main/java/semicolon/viewtist/chatting/entity/type/Status.java
  domain/src/main/java/semicolon/viewtist/chatting/repository/ChatRoomRepository.java
  domain/src/main/java/semicolon/viewtist/global/exception/ErrorCode.java
Labels: feature

#34 [refactor] securityConfig && refreshToken 설정
  common/src/main/java/semicolon/viewtist/config/SecurityConfig.java
  common/src/main/java/semicolon/viewtist/config/SwaggerConfig.java
  common/src/main/java/semicolon/viewtist/oauth/handler/OAuth2SuccessHandler.java
  common/src/main/java/semicolon/viewtist/user/controller/AuthController.java
  common/src/main/java/semicolon/viewtist/user/controller/UserController.java
  common/src/main/java/semicolon/viewtist/user/service/AuthService.java
  common/src/main/java/semicolon/viewtist/user/service/UserService.java
  domain/src/main/java/semicolon/viewtist/global/exception/ErrorCode.java
  domain/src/main/java/semicolon/viewtist/jwt/CustomAccessDeniedHandler.java
  domain/src/main/java/semicolon/viewtist/jwt/CustomAuthenticationEntryPoint.java
  domain/src/main/java/semicolon/viewtist/jwt/TokenProvider.java
  domain/src/main/java/semicolon/viewtist/user/dto/request/SocialUserRequest.java
  domain/src/main/java/semicolon/viewtist/user/dto/request/UpdateMypage.java
  domain/src/main/java/semicolon/viewtist/user/dto/response/SigninResponse.java
  domain/src/main/java/semicolon/viewtist/user/dto/response/UserResponse.java
  domain/src/main/java/semicolon/viewtist/user/entity/User.java
Labels: feature, fix

#35 [#37] streaming-api 업데이트
  domain/src/main/java/semicolon/viewtist/liveStreaming/entity/Category.java
  domain/src/main/java/semicolon/viewtist/liveStreaming/entity/LiveStreaming.java
  streaming-api/src/main/java/semicolon/viewtist/config/SecurityConfig.java
  streaming-api/src/main/java/semicolon/viewtist/config/SwaggerConfig.java
  streaming-api/src/main/java/semicolon/viewtist/cotroller/LiveStreamingController.java
  streaming-api/src/main/java/semicolon/viewtist/service/LiveStreamingService.java
Labels: feature, fix

#37 [refactor] refreshToken 수정
  common/src/main/java/semicolon/viewtist/CommonApplication.java
  common/src/main/java/semicolon/viewtist/oauth/OAuth2UserServiceImplement.java
  common/src/main/java/semicolon/viewtist/oauth/handler/OAuth2SuccessHandler.java
  common/src/main/java/semicolon/viewtist/user/controller/UserController.java
  common/src/main/java/semicolon/viewtist/user/service/AuthService.java
  common/src/main/java/semicolon/viewtist/user/service/SchedulerService.java
  common/src/main/java/semicolon/viewtist/user/service/UserService.java
  domain/src/main/java/semicolon/viewtist/jwt/TokenProvider.java
  domain/src/main/java/semicolon/viewtist/jwt/entity/RefreshToken.java
  domain/src/main/java/semicolon/viewtist/jwt/repository/RefreshTokenRepository.java
  domain/src/main/java/semicolon/viewtist/jwt/repository/TokenBlacklistRepository.java
  domain/src/main/java/semicolon/viewtist/user/dto/request/UpdateIntroduction.java
  domain/src/main/java/semicolon/viewtist/user/dto/request/UpdateNickname.java
  domain/src/main/java/semicolon/viewtist/user/entity/User.java
Labels: refactor

#39 [#38] Streaming-api 검색기능 구현
  domain/src/main/java/semicolon/viewtist/global/exception/ErrorCode.java
  domain/src/main/java/semicolon/viewtist/global/exception/GlobalExceptionHandler.java
  domain/src/main/java/semicolon/viewtist/liveStreaming/dto/response/LiveStreamingResponse.java
  streaming-api/src/main/java/semicolon/viewtist/cotroller/LiveStreamingController.java
  streaming-api/src/main/java/semicolon/viewtist/service/LiveStreamingService.java
Labels: feature

#40 [refactor] 프로필 default 값 넣기
  common/src/main/java/semicolon/viewtist/user/controller/UserController.java
  common/src/main/java/semicolon/viewtist/user/service/AuthService.java
  common/src/main/java/semicolon/viewtist/user/service/SchedulerService.java
  common/src/main/java/semicolon/viewtist/user/service/UserService.java
  domain/src/main/java/semicolon/viewtist/jwt/entity/TokenBlacklist.java
  domain/src/main/java/semicolon/viewtist/jwt/repository/TokenBlacklistRepository.java
  domain/src/main/java/semicolon/viewtist/user/dto/request/SocialUserRequest.java
  domain/src/main/java/semicolon/viewtist/user/dto/request/UserSignupRequest.java
  domain/src/main/java/semicolon/viewtist/user/entity/User.java
Labels: feature, fix, refactor

#48 [#53] 구독과 알림기능
  chatting-api/build.gradle
  chatting-api/src/main/java/semicolon/viewtist/ChattingApplication.java
  common/src/main/java/semicolon/viewtist/CommonApplication.java
  common/src/main/java/semicolon/viewtist/user/controller/SubscribeController.java
  common/src/main/java/semicolon/viewtist/user/controller/UserController.java
  common/src/main/java/semicolon/viewtist/user/service/SubscribeService.java
  common/src/main/java/semicolon/viewtist/user/service/UserService.java
  domain/src/main/java/semicolon/viewtist/global/exception/ErrorCode.java
  domain/src/main/java/semicolon/viewtist/global/exception/GlobalExceptionHandler.java
  domain/src/main/java/semicolon/viewtist/sse/dto/response/NotifyStreamingResponse.java
  domain/src/main/java/semicolon/viewtist/sse/entity/Notify.java
  domain/src/main/java/semicolon/viewtist/sse/entity/Subscribe.java
  domain/src/main/java/semicolon/viewtist/sse/repository/EmitterRepository.java
  domain/src/main/java/semicolon/viewtist/sse/repository/EmitterRepositoryImpl.java
  domain/src/main/java/semicolon/viewtist/sse/repository/NotifyRepository.java
  domain/src/main/java/semicolon/viewtist/sse/repository/SubscribeRepository.java
  domain/src/main/java/semicolon/viewtist/sse/service/NotifyService.java
  domain/src/main/java/semicolon/viewtist/user/dto/request/UserSignupRequest.java
  domain/src/main/java/semicolon/viewtist/user/dto/response/SubscribeResponse.java
  domain/src/main/java/semicolon/viewtist/user/exception/SubscribeException.java
  streaming-api/src/main/java/semicolon/viewtist/LiveStreamingApplication.java
  streaming-api/src/main/java/semicolon/viewtist/controller/LiveStreamingController.java
  streaming-api/src/main/java/semicolon/viewtist/controller/NotifyController.java
  streaming-api/src/main/java/semicolon/viewtist/service/LiveStreamingService.java
Labels: feature

#50 [# 48]Feature/chat room ssl을 적용하여 https와 wss 통신 가능하도록 기능 추가
  chatting-api/src/main/java/semicolon/viewtist/ChattingApplication.java
  chatting-api/src/main/java/semicolon/viewtist/controller/ChatMessageController.java
  chatting-api/src/main/java/semicolon/viewtist/controller/ChatRoomController.java
  chatting-api/src/main/java/semicolon/viewtist/service/ChatMessageService.java
  chatting-api/src/main/java/semicolon/viewtist/service/ChatRoomService.java
  chatting-api/src/main/java/semicolon/viewtist/websocket/WebSocketChatHandler.java
  common/src/main/java/semicolon/viewtist/user/service/AuthService.java
  domain/src/main/java/semicolon/viewtist/chatting/dto/response/ChatRoomResponse.java
  domain/src/main/java/semicolon/viewtist/chatting/entity/ChatRoom.java
  domain/src/main/java/semicolon/viewtist/chatting/repository/ChatRoomRepository.java
  domain/src/main/java/semicolon/viewtist/liveStreaming/dto/request/LiveStreamingCreateRequest.java
  domain/src/main/java/semicolon/viewtist/liveStreaming/dto/response/LiveStreamingResponse.java
  domain/src/main/java/semicolon/viewtist/liveStreaming/entity/LiveStreaming.java
  domain/src/main/java/semicolon/viewtist/user/entity/User.java
  domain/src/main/java/semicolon/viewtist/user/repository/UserRepository.java
  streaming-api/src/main/java/semicolon/viewtist/LiveStreamingApplication.java
  streaming-api/src/main/java/semicolon/viewtist/service/LiveStreamingService.java
Labels: feature, refactor
